name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest || echo "No tests found, skipping."

      - name: Build Docker image
        run: |
          docker build -t travel-agent-chatbot .

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" . $USER@$HOST:~/Travel-Agent-Chat-Bot
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd ~/Travel-Agent-Chat-Bot
            if [ ! -z "$ENV_VARS" ]; then
              echo "$ENV_VARS" > .env
            fi
            docker build -t travel-agent-chatbot .
            docker rm -f travel-agent-chatbot || true
            if [ -f .env ]; then
              docker run -d --env-file .env -p 7000:5000 --name travel-agent-chatbot travel-agent-chatbot
            else
              docker run -d -p 7000:5000 --name travel-agent-chatbot travel-agent-chatbot
            fi
            sleep 5
            curl -f http://localhost:5000 || echo "Warning: App may not be running"
          EOF
          rm key.pem
